version: '2'
services:
  mysqldb:
    build: ./db-services
    restart: unless-stopped
  webapp:
    build: ./nodejs-services
    ports:
     - "5000:5000"
    depends_on:
     - mysqldb
    environment:
     - DATABASE_HOST=mysqldb
    volumes:
     - ./nodejs-services:/app