version: '2.1'
services:
  mysqldb:
    build: ./db-services
    ports:
     - "3306:3306"
    environment:
     - DATABASE_HOST=mysqldb
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  webapp:
    build: ./nodejs-services
    ports:
     - "5000:5000"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
     - DATABASE_HOST=mysqldb
     - DBNAME=studentsdb
     - DATABASE_USER=student
     - DATABASE_PWD=student123
    volumes:
     - ./nodejs-services:/app