version: '2'
services:
  mysqldb:
    build: ./db-services
    ports:
    - "3306:3306"
    environment:
     - DATABASE_HOST=mysql
     - MYSQL_ROOT_PASSWORD=secretadmin
     - MYSQL_DATABASE=studentsdb
     - MYSQL_USER=student
     - MYSQL_PASSWORD=student123
  webapp:
    build: ./nodejs-services
    ports:
     - "5000:5000"
    depends_on:
     - mysqldb
    environment:
     - DATABASE_HOST=mysql
     - DBNAME=studentsdb
     - DATABASE_USER=student
     - DATABASE_PWD=student123
    volumes:
     - ./nodejs-services:/app