version: '3.3'
services:
  mysqldb:
    build: ./db-services
    restart: always
    environment:
      DATABASE_HOST: 'mysqldb'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
  webapp:
    build: ./nodejs-services
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb
    environment:
      DATABASE_HOST: 'mysqldb'
      DBNAME: 'studentsdb'
      DATABASE_USER: 'student'
      DATABASE_PWD: 'student123'
    volumes:
      - ./nodejs-services:/app