version: '2'
services:
  mysqldb:
    build: ./db-services
    environment:
     - DATABASE_HOST=mysqldb
     - DATABASE_ROOT_PWD=secretadmin
     - MYSQL_DATABASE=studentsdb
     - MYSQL_USER=student
     - MYSQL_PASSWORD=student123
    restart: unless-stopped
  webapp:
    build: ./nodejs-services
    ports:
     - "5000:5000"
    depends_on:
     - mysqldb
    environment:
     - DATABASE_HOST=mysqldb
     - DATABASE_ROOT_PWD=secretadmin
     - DBNAME=studentsdb
    volumes:
     - ./nodejs-services:/app